### ISSUE TITLE
PSCloudShell - PSCloudShell - Cannot login

### ISSUE THREAD

**Issue by NillsF** [PowerShell/PSCloudShell#4]
Hi,

I cannot login to the powershell cloud shell. I created a storage account in West US as required. Logging in doesn't succeed for now.

![image](https://user-images.githubusercontent.com/6205923/27469455-ede72660-57ef-11e7-8dfe-c5c68b2b17e7.png)

**Comment by mirichmo** [comment]
Thanks for the report. We have had a few others report this issue via our Slack channel and we are looking into it.

**Comment by HemantMahawar** [comment]
This issue has been fixed. Please open new issues in [Azure Cloud Shell Feedback](https://aka.ms/cloudshellfeedback)
