### ISSUE TITLE
Can you Transfer files from on Premises To Azure using CloudShell?

### ISSUE THREAD

**Issue by crshnbrn66** [PowerShell/PSCloudShell#6]

**Comment by HemantMahawar** [comment]
@crshnbrn66 Yes. See the blog post that shows how to mount the clouddrive on your local machine - https://noelbundick.com/2017/05/13/Supercharging-the-Azure-Cloud-Shell. 

Does this answers your question?

**Comment by crshnbrn66** [comment]
awesome yes. it does one other question has there been anything added to VSTS or TFS for tasks to push builds to Azure using this technology?

**Comment by HemantMahawar** [comment]
@crshnbrn66 Not yet. I would be interested to know more about VSTS/TFS scenario so I can start investigation.

**Comment by crshnbrn66** [comment]
So lets say I'm building a web application on premises or in some other Version control that I need to push files from X location during a Deploy / build / Release process and   I've  decided to use VSTS as my means to push these files. That is the scenario I'm trying to figure out if something has already been build for VSTS or TFS in terms of a task to do that.  

https://github.com/Microsoft/vsts-tasks

**Comment by CarnegieJ** [comment]
@crshnbrn66  You may want to visit the following link to find extensions for Visual Studio Team Services (VSTS) to provide Build and Release tasks with integration to several source control systems, 
[](<https://marketplace.visualstudio.com/search?target=VSTS&category=Build%20and%20release>)

Kind regards,
CarnegieJ

**Comment by crshnbrn66** [comment]
I hadn't seen anything there yet... that was the reason for the question.

**Comment by HemantMahawar** [comment]
No action needed. Question has been answered.
